#!/bin/sh

if [ "$#" -ne 3 ]; then
	echo "Invalid number of arguments received ($#). 3 expected"
	exit 1
fi

TYPE=$1
SUBJECT=$2
FILENAME=$3

mkdir -p "$TYPE/$SUBJECT"

# CREATE TYPE DIR AND SUMMARY
if test -f "$TYPE/summary.md"; then
	echo "Type exists"
else
	echo "[..](../notes.md)" > "$TYPE/summary.md"
	sed -i -e "\$a[$TYPE]($TYPE/summary.md)" notes.md
fi

# CREATE SUBJECT FILE
if test -f "$TYPE/$SUBJECT.md"; then
	echo "Subject exists"
else
	echo "[..](summary.md)" > "$TYPE/$SUBJECT.md"
	sed -i -e "\$a[$SUBJECT]($SUBJECT.md)" "$TYPE/summary.md"
fi

if test -f "$TYPE/$SUBJECT/$FILENAME.md"; then
	echo "Note with this name already exists under the given subject."
	exit 1
fi

echo "[..](../$SUBJECT.md)" > $TYPE/$SUBJECT/$FILENAME.md

sed -i -e "\$a[$FILENAME]($SUBJECT/$FILENAME.md)" $TYPE/$SUBJECT.md

nvim $TYPE/$SUBJECT/$FILENAME.md
